### ISSUE TITLE
auスマートパスPlayストア配信対応 スマートパス会員判定API作成仕様書

### ISSUE THREAD

**Issue by ZinMin095793** [agendaPD/ausmartpass_doc#1]
お疲れ様です。
auスマートパス会員判定APIのIF仕様書を作成しました。
処理フローもざっくり作成しました。
お手数ですが、確認をお願いいたします。
[au_smartpass_API.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5587391/au_smartpass_API.xlsx)

**Comment by tsujimura-agenda** [comment]
■全体
更新者、更新日時を記載してください。

■モジュール構成
①②③が何を表しているのか記載してください。

**Comment by masayukihoshino** [comment]
「auスマートパス会員判定API」シート
入力パラメータ
　"memory"または"tools"固定
今後対応アプリが増えることを考慮して表形式にまとめて「概要」シートに書いてください。
表の列はパラメータ名と認証API(通常会員判定APIorプレミアム会員判定APIか)２つで。

「API呼び出し結果URL」シート
resultcode
今後プレミアム会員判定結果を返す必要が出てくる場合を考慮して、
・プレミアム会員
・通常会員
・未加入
の3パターンをAPIに返す仕様にしてください。

**Comment by masayukihoshino** [comment]
ドメインは同じです(www2.sourcenext.com)
サーバは新たに構築するので変更してください。
　筆王サーバ→auスマートパス会員判定APIサーバ

**Comment by masayukihoshino** [comment]
>今後対応アプリが増えることを考慮して表形式にまとめて「概要」シートに書いてください。
表の列はパラメータ名と認証API(通常会員判定APIorプレミアム会員判定APIか)２つで。

[RMSライセンスマッチサーバ機能仕様書.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5588034/RMS.xlsx)
これの概要シートの表を参考にしてください。

**Comment by masayukihoshino** [comment]
テスト

**Comment by ZinMin095793** [comment]
お疲れ様です。
レビュー指摘を対応しました。
各シートの概要も記載しました。
お手数ですが、確認をお願いいたします。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5593656/au_smartpass_api.xlsx)

**Comment by tsujimura-agenda** [comment]
■概要シートの表に関して
・背景色、枠線を統一させてください。
・表の内容ですが、以下を記載してください。
　製品名→今のままで良いです
　入力パラメータ(productname)→"memory" or "tools"
　認証API→auスマートパス契約状態確認(Oauth版)要求APIのURL("https://auth.au-market.com/pass/AuthSpUser" or "https://auth.au-market.com/pass/AuthSpPrmUser")

**Comment by tsujimura-agenda** [comment]
■auスマートパス会員判定APIシートの46行目
アプリごとに、呼び出すauスマートパス契約状態確認APIが異なる事を記載してください。

**Comment by masayukihoshino** [comment]
■auスマートパス会員判定APIシートの21行目の入力制限
詳細は概要シート参照するよう修正してください。
備考欄の記載は消してください。

**Comment by ZinMin095793** [comment]
ご確認ありがとうございます。
レビュー指摘を対応しました。
修正した箇所に黄色を付けました。
確認をお願いいたします。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5594146/au_smartpass_api.xlsx)

**Comment by tsujimura-agenda** [comment]
> 
> 
> ■概要シートの表に関して
> ・背景色、枠線を統一させてください。
> ・表の内容ですが、以下を記載してください。
> 　製品名→今のままで良いです
> 　入力パラメータ(productname)→"memory" or "tools"
> 　認証API→auスマートパス契約状態確認(Oauth版)要求APIのURL("https://auth.au-market.com/pass/AuthSpUser" or "https://auth.au-market.com/pass/AuthSpPrmUser")

指摘の仕方が悪かったようですね…。

■表には、以下の3項目を記載
・製品名
・入力パラメータ(productname)
・認証API

■製品名
製品名を記載する。
驚速メモリと超便利ツールズを記載する。

■入力パラメータ(productname)
製品ごとの値を記載する。
驚速メモリなら"memory"を、超便利ツールズなら"tools"を記載する。

■認証API
製品ごとの値を記載する。
驚速メモリも超便利ツールズも、"https://auth.au-market.com/pass/AuthSpUser"を記載する。

**Comment by ZinMin095793** [comment]
ご確認ありがとうございます。
レビュー指摘を対応しました。
確認をお願いいたします。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5594431/au_smartpass_api.xlsx)

**Comment by tsujimura-agenda** [comment]
私からはありません。

**Comment by masayukihoshino** [comment]
概要シートの認証APIですがURLだけだとわかりにくいです。
通常の会員判定APIなのかプレミアム会員判定APIなのか追記してください。

**Comment by masayukihoshino** [comment]
軽微なので再レビュ不要です。

**Comment by masayukihoshino** [comment]
@tsujimura-agenda 
テストケース作成進めるか環境構築進めるか、どちらを先に進める方がよいか、
辻村さんの方で判断して指示出してください。

実装は12/7くらいにFIXしていればよいです。
設計書はテストがないだけなので、SOURCEさんに送付します。

**Comment by tsujimura-agenda** [comment]
@ZinMin095793 
実装を優先させてください。
実装完了後、テスト設計してください。
テスト設計の時間も考慮して実装完了させてください。

**Comment by tsujimura-agenda** [comment]
@ZinMin095793 
テスト設計は、このissueではなく、別レビューであげてください。

**Comment by ZinMin095793** [comment]
@tsujimura-agenda 
上記の件、承知いたしました。
実装を優先します。

>概要シートの認証APIですがURLだけだとわかりにくいです。
通常の会員判定APIなのかプレミアム会員判定APIなのか追記してください。

上記の指摘を対応しました。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5594523/au_smartpass_api.xlsx)

**Comment by tsujimura-agenda** [comment]
> 上記の指摘を対応しました。

プレミアム会員判定APIを使用するアプリが増えた場合、どう記載するのでしょうか？

**Comment by ZinMin095793** [comment]
>プレミアム会員判定APIを使用するアプリが増えた場合、どう記載するのでしょうか？

API URLの後ろに記載するようにします。

**Comment by ZinMin095793** [comment]
お疲れ様です。
修正しました。
よろしくお願いいたします。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5594970/au_smartpass_api.xlsx)

**Comment by tsujimura-agenda** [comment]
私からはありません。

**Comment by masayukihoshino** [comment]
モジュール構成で1点だけ。
今回iosアプリはないのでiosの記載は削除しておいてください。Playストア(android)のみです。

**Comment by masayukihoshino** [comment]
軽微なので再レビュ不要です。

**Comment by ZinMin095793** [comment]
>モジュール構成で1点だけ。
今回iosアプリはないのでiosの記載は削除しておいてください。Playストア(android)のみです。

ご確認ありがとうございます。
レビュー指摘を対応しました。修正した箇所に紫色を付けました。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5595568/au_smartpass_api.xlsx)

**Comment by masayukihoshino** [comment]
細かくて申し訳ないのですが、以下修正お願い致します。
・概要シートの「対応製品名と認証API」ですが、今後対応アプリが増えた場合はこの表に追記する旨を書いてください。
・モジュール構成シートの構成図内の「auスマートパス会員判定APIサーバ」という文言がと矩形が若干かぶっています。
・auスマートパス会員判定APIシートの概要欄の文言ですが、改行不要な行は1行で書いてください。(7、8行目など)
・auスマートパス会員判定APIシートの概要に次の点を追記してください。
　呼び出し元のアプリにより通常会員判定APIとプレミアム会員判定APIどちらかをコールする。
　ユーザがログインキャンセルした場合などはエラーを返す。
　返却値の詳細は「API呼び出し結果URL」シートを参照する。

**Comment by ZinMin095793** [comment]
お疲れ様です。
上記のレビュー指摘を対応しました。修正した箇所を緑色付けました。
お手数をおかけしますが、確認をお願いいたします。
[au_smartpass_api.xlsx](https://github.com/agendaPD/ausmartpass_doc/files/5600315/au_smartpass_api.xlsx)

**Comment by masayukihoshino** [comment]
OKです。
色戻してmasterに反映してください。

**Comment by ZinMin095793** [comment]
ご確認、ありがとうございます。
色外してmasterに反映しました。

**Comment by ZinMin095793** [comment]
対応済みですので、閉じます。
